[project]
name = "padel-cv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chumpy>=0.70",
    "imageio>=2.37.2",
    "ipykernel<7",
    "ipywidgets>=8.1.7",
    "matplotlib>=3.10.7",
    "mmcv",
    "mmdet",
    "mmengine",
    "mmpose",
    "onnxruntime>=1.19.0",
    "notebook>=7.4.7",
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "openmim>=0.3.9",
    "pyside6>=6.7.3",
    "pandas>=2.3.3",
    "pip>=25.3",
    "pytorchvideo>=0.1.5",
    "rtmlib>=0.0.14",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "timm>=1.0.22",
    "torch>=2.9.0",
    "torchvision>=0.24.0",
    "transformers>=4.57.3",
    "ultralytics>=8.3.223",
    "google-cloud-storage>=2.18.2",
    "xtcocotools",
]

[tool.uv.extra-build-dependencies]
chumpy = ["pip"]
mmdet = ["torch"]

[tool.uv.sources]
xtcocotools = { git = "https://github.com/jin-s13/xtcocoapi" }
mmengine = { git = "https://github.com/open-mmlab/mmengine" }
mmcv = { git = "https://github.com/open-mmlab/mmcv", tag = "v2.1.0" }
mmdet = { git = "https://github.com/open-mmlab/mmdetection", tag = "v3.2.0" }
mmpose = { git = "https://github.com/open-mmlab/mmpose" }

[tool.ruff.lint]
ignore = ["F541"]
